server:
  port: 8001
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: nacos.lwk4you.com
        namespace: lwk-dev
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://106.53.64.109:3306/spring_cloud?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lwk123456
seata:
  use-jdk-proxy: true
